export const COUNTRY_GET_DATA = 'COUNTRY_GET_DATA';
export const COUNTRY_SET_VISIBLE = 'COUNTRY_SET_VISIBLE';
export const COUNTRY_DELETE = 'COUNTRY_DELETE';
export const COUNTRY_DELETE_ALL = 'COUNTRY_DELETE_ALL';
export const COUNTRY_SET_STATUS = 'COUNTRY_SET_STATUS';

